# Generated by Django 3.1.5 on 2021-05-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemaster',
            old_name='name',
            new_name='articlename',
        ),
        migrations.RenameField(
            model_name='companyledgermaster',
            old_name='name',
            new_name='comname',
        ),
        migrations.RenameField(
            model_name='departmentmaster',
            old_name='name',
            new_name='depname',
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Rate_per_unit', models.IntegerField()),
                ('Unit', models.CharField(choices=[('1', 'KG'), ('2', 'METRE')], default='1', max_length=20)),
                ('articlename', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.articlemaster', verbose_name='ArticleName')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.colormaster', verbose_name='Colorname')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.IntegerField()),
                ('transaction_status', models.CharField(choices=[('1', 'PENDING'), ('2', 'COMPLETED'), ('3', 'CLOSE')], default='1', max_length=20)),
                ('Remark', models.CharField(blank=True, max_length=100)),
                ('comname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.companyledgermaster', verbose_name='CompanyLedgerName')),
                ('depname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.departmentmaster', verbose_name='departmentName')),
                ('short_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.branchmaster', verbose_name='BranchName')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grossquantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('netquantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Unit', models.CharField(choices=[('1', 'KG'), ('2', 'METRE')], default='1', max_length=20)),
                ('articlename', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.articlemaster', verbose_name='ArticleName')),
                ('comname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.companyledgermaster', verbose_name='CompanyLedgerName')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.colormaster', verbose_name='Colorname')),
            ],
        ),
    ]
