# Generated by Django 3.1.5 on 2021-05-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20210502_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='InventoryItem_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Transaction_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='TransactionDetail_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
